#baseURL = 'http://example.org/'
languageCode = 'it'
title = 'Picchi Di Prestigio'
theme="gohugo-theme-ananke"
canonifyURLs = true

SectionPagesMenu = "main"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Il primo blog italiano a gestione distribuita per appassionati di montagna"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3





